export const environment = {
  production: true,
 // API_URL: 'http://18.222.26.198:7002/',
  download_shatter_url: 'http://shatterblok.com/testpdf/html2pdf/shatterblok-agreement.php?id=',
  download_artistxp_url: 'http://shatterblok.com/testpdf/html2pdf/artistxp-agreement.php?id=',
  Pdf_link: '&environment=live',
  loginurl: 'https://shatterblok.com/',
  contact_us_url: 'https://shatterblok.com/contact-us',
  API_URL: 'https://nodessl.influxiq.com:6033/',
  Audiodeadline_API_URL: 'https://api.audiodeadline.com:6004/',
  // resetpaswordurl: 'http://shatterblokbackend.com.s3-website.us-east-2.amazonaws.com/',
  resetpaswordurl: 'http://backoffice.shatterblok.com/',
  uplodeimg_url: 'https://api.audiodeadline.com/nodeserver/uploads/modelimages/',
  // uplodeimg_url: 'https://shatterblok.com/upload/modelimages/',
  audio_img_url: 'https://api.audiodeadline.com:6003/',
  audio_img_folder_url: 'https://api.audiodeadline.com/nodeserver/uploads/banner/',
  audiodeadline_php_url: 'https://api.audiodeadline.com/',
  artistxp_php_url: 'http://share.artistxp.com/',
  artistxp_url: 'share.artistxp.com',
  audiodeadline_fileurl : 'https://api.audiodeadline.com/nodeserver/uploads/',
  environment: "production",
  brandfolder: 'brandimages',
  modelfolder: 'modelimages',
  Brand_Image_Url: 'https://api.audiodeadline.com/nodeserver/uploads/brandimages',
  Model_Image_Url: 'https://api.audiodeadline.com/nodeserver/uploads/modelimages',
  domain_for_fileupload: 'https://api.audiodeadline.com:6031/',
  artistxpsharesignupurl: 'https://artistxp.com/',
  audiodeadlineshareticketsaleurl: 'https://audiodeadline.com/',
};
