/**
 * Created by debasiskar on 18/03/19.
 */

export const environment = {
    production: false,
   // API_URL: 'http://nodessl.influxiq.com:7012/',
   // API_URL: 'http://18.222.26.198:7002/',
    download_shatter_url: 'http://shatterblok.com/testpdf/html2pdf/shatterblok-agreement.php?id=',
    download_artistxp_url: 'http://shatterblok.com/testpdf/html2pdf/artistxp-agreement.php?id=',
    Pdf_link: '&environment=development',
    loginurl: 'https://development.shatterblok.com/',
    contact_us_url: 'https://development.shatterblok.com/contact-us',
    API_URL: 'https://nodessl.influxiq.com:6053/',
    Audiodeadline_API_URL: 'https://developmentapi.audiodeadline.com:6090/',
   // resetpaswordurl: 'http://development.shatterblokbackend.com.s3-website.us-east-2.amazonaws.com/',
    resetpaswordurl: 'https://developmentbackoffice.shatterblok.com/',
    // uplodeimg_url: 'https://shatterblok.com/upload/modelimages/',
    uplodeimg_url: 'https://developmentapi.audiodeadline.com/nodeserver/uploads/modelimages/',
   // audio_img_url: 'http://developmentapi.audiodeadline.com:3008/',
    audio_img_url: 'https://developmentapi.audiodeadline.com:6090/',
    audio_orderdetails: 'https://developmentapi.audiodeadline.com:6004/',
    audio_img_folder_url: 'https://developmentapi.audiodeadline.com/nodeserver/uploads/banner/',
    audiodeadline_php_url: 'https://developmentapi.audiodeadline.com/',
    audiodeadline_url: 'developmentapi.audiodeadline.com/',
    artistxp_php_url: 'http://devshare.artistxp.com/',
    artistxp_url: 'devshare.artistxp.com',
    //audiodeadline_dev_php_url: 'https://api.audiodeadline.com/',
    audiodeadline_fileurl : 'https://developmentapi.audiodeadline.com/nodeserver/uploads/',
    environment: 'development',
    brandfolder: 'brandimages',
    modelfolder: 'modelimages',
    Brand_Image_Url: 'https://developmentapi.audiodeadline.com/nodeserver/uploads/brandimages',
    Model_Image_Url: 'https://developmentapi.audiodeadline.com/nodeserver/uploads/modelimages',
 //   domain_for_fileupload: 'http://developmentapi.audiodeadline.com:7031/',
    domain_for_fileupload: 'https://developmentapi.audiodeadline.com:6031/',
    artistxpsharesignupurl: 'https://development.artistxp.com/',
    audiodeadlineshareticketsaleurl: 'https://development.audiodeadline.com/',
};
